import React from 'react';
export const metadata = {
        title: "All Post",
        description: "Generated by create next app",
    };

const page = () => {
    return (
        <div>
            This is Post page
        </div>
    );
};

export default page;