import { Geist, Geist_Mono,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";

const poppins= Poppins({
  weight:["400","600","700"],
  subsets: ["latin"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Learning NextJS",
    template: "%s | Learning NextJS"
  },
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "Web Development"],
  authors: [{ name: "Mezbahul Islam" }],
  creator: "Mezbahul Islam",
  publisher: "MyApp",
  robots: "index, follow"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${poppins.className}`}
      >
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
