import React from "react";

export async function generateMetadata({ params }) {
    const p = await params;
  return {
    title: `ID: ${p.id}`,
    description: "Generated by create next app",
  };
}

const Page = async ({ params }) => {
    const p = await params;
  return (
    <div>
      ID: {p.id}
    </div>
  );
};

export default Page;
